apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    name: web-server
  name: web-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: web-server
    spec:
      containers:
      - name: node
        image: __IMAGETAG__
        env:
        - name: SERVER_ID  #export the pod ID as SERVER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MONGO_URL
          value: "mongodb://mongo:27017/"
        resources:
          requests:
            memory: "64Mi"
            cpu: "80m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe: # time to come alive (only at startup)
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe: # check if app is alive (during executino)
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: hello-world-service
  name: hello-world-service
spec:
  ports:
  - name: http
    port: 8080
    nodePort: 30006
  selector:
    name: web-server
  type: NodePort
